apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-sql
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS equation_db;
    USE equation_db;
    CREATE TABLE IF NOT EXISTS equation_results (
      id INT AUTO_INCREMENT PRIMARY KEY,
      a FLOAT NOT NULL,
      b FLOAT NOT NULL,
      c FLOAT NOT NULL,
      d FLOAT NOT NULL,
      result FLOAT NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );