apiVersion: apps/v1
kind: Deployment
metadata:
  name: resta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resta
  template:
    metadata:
      labels:
        app: resta
    spec:
      containers:
      - name: resta
        image: [chocomil]/equation-resta:latest
        ports:
        - containerPort: 8000